/*
 * Everywhere
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-09-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pro.travelin.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ProTravelinItenerarySummariesMember
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-07T11:22:55.420-04:00[America/New_York]")
public class ProTravelinItenerarySummariesMember {
  public static final String SERIALIZED_NAME_ITENERARY_ID = "iteneraryId";
  @SerializedName(SERIALIZED_NAME_ITENERARY_ID)
  private String iteneraryId;


  public ProTravelinItenerarySummariesMember iteneraryId(String iteneraryId) {
    
    this.iteneraryId = iteneraryId;
    return this;
  }

   /**
   * Get iteneraryId
   * @return iteneraryId
  **/
  @ApiModelProperty(required = true, value = "")

  public String getIteneraryId() {
    return iteneraryId;
  }



  public void setIteneraryId(String iteneraryId) {
    this.iteneraryId = iteneraryId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProTravelinItenerarySummariesMember proTravelinItenerarySummariesMember = (ProTravelinItenerarySummariesMember) o;
    return Objects.equals(this.iteneraryId, proTravelinItenerarySummariesMember.iteneraryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iteneraryId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProTravelinItenerarySummariesMember {\n");
    sb.append("    iteneraryId: ").append(toIndentedString(iteneraryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

