/*
 * Everywhere
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-09-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pro.travelin.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import pro.travelin.model.ProTravelinGetIteneraryOutputIteneraryMember;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2002
 */
public class InlineResponse2002Test {
    private final InlineResponse2002 model = new InlineResponse2002();

    /**
     * Model tests for InlineResponse2002
     */
    @Test
    public void testInlineResponse2002() {
        // TODO: test InlineResponse2002
    }

    /**
     * Test the property 'itenerary'
     */
    @Test
    public void iteneraryTest() {
        // TODO: test itenerary
    }

}
