/*
 * Everywhere
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-09-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pro.travelin.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProTravelinItenerarySummariesMember
 */
public class ProTravelinItenerarySummariesMemberTest {
    private final ProTravelinItenerarySummariesMember model = new ProTravelinItenerarySummariesMember();

    /**
     * Model tests for ProTravelinItenerarySummariesMember
     */
    @Test
    public void testProTravelinItenerarySummariesMember() {
        // TODO: test ProTravelinItenerarySummariesMember
    }

    /**
     * Test the property 'iteneraryId'
     */
    @Test
    public void iteneraryIdTest() {
        // TODO: test iteneraryId
    }

}
