/*
 * Everywhere
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-09-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pro.travelin.api;

import pro.travelin.invoker.ApiException;
import java.math.BigDecimal;
import pro.travelin.model.InlineResponse200;
import pro.travelin.model.InlineResponse2001;
import pro.travelin.model.InlineResponse404;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIteneraryTest() throws ApiException {
        String iteneraryId = null;
        InlineResponse2001 response = api.getItenerary(iteneraryId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listItenerariesTest() throws ApiException {
        BigDecimal limit = null;
        String nextToken = null;
        InlineResponse200 response = api.listIteneraries(limit, nextToken);

        // TODO: test validations
    }
    
}
